# Generated by Django 3.0.7 on 2020-07-09 10:06

import blog_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_auto_20200702_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=blog_api.models.get_image_path),
        ),
    ]
