# Generated by Django 3.0.7 on 2020-06-28 06:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(max_length=5000, null=True)),
                ('post_img', models.ImageField(blank=True, null=True, upload_to=api.models.get_image_path)),
                ('tag', models.ManyToManyField(blank=True, to='api.Tag')),
            ],
        ),
    ]
